name: Docker Build And Push To Docker Hub

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Build TEMPERATURE CONVERSION
    runs-on: ubuntu-latest
    environment: production
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: secrets.DOCKERHUB_USERNAME/secrets.DOCKERHUB_NAMEIMAGE:latest